version: "3.8"

services:
  crdb-0:
    container_name: crdb-0
    hostname: crdb-0
    image: cockroachdb/cockroach:latest
    command: start-single-node --cluster-name=auth-haproxy --logtostderr=WARNING --log-file-verbosity=WARNING --insecure
    restart: always
    networks:
      - db

  crdb-1:
    container_name: crdb-1
    hostname: crdb-1
    image: cockroachdb/cockroach:latest
    command: start --cluster-name=auth-haproxy --logtostderr=WARNING --log-file-verbosity=WARNING --insecure --join=crdb-0
    depends_on:
      - crdb-0
    restart: always
    networks:
      - db

  crdb-2:
    container_name: crdb-2
    hostname: crdb-2
    image: cockroachdb/cockroach:latest
    command: start --cluster-name=auth-haproxy --logtostderr=WARNING --log-file-verbosity=WARNING --insecure --join=crdb-0
    depends_on:
      - crdb-0
    restart: always
    networks:
      - db

  crdb-lb:
    container_name: crdb-lb
    hostname: crdb-lb
    image: timveil/dynamic-haproxy:latest
    ports:
      - "1080:8080"
      - "1081:8081"
      - "26257:26257" # Remove on production. Setup for goserver
    environment:
      - NODES=crdb-0 crdb-1 crdb-2
    depends_on:
      - crdb-0
      - crdb-1
      - crdb-2
    restart: always
    networks:
      - db
      - backend

  crdb-init:
    container_name: crdb-init
    hostname: crdb-init
    image: timveil/cockroachdb-remote-client:latest
    environment:
      - COCKROACH_HOST=crdb-0:26257
      - COCKROACH_INSECURE=true
      - DATABASE_NAME=auth
      - DATABASE_USER=authUser
    depends_on:
      - crdb-lb
    networks:
      - db

  server-0:
    container_name: server-0
    image: node:latest
    command: npm start
    volumes:
      - ./package.json:/usr/app/package.json
      - ./package-lock.json:/usr/app/package-lock.json
      - ./server:/usr/app/server
      - /usr/app/node_modules
      - ./volumes/server-0/logs:/tmp/app/logs
    working_dir: /usr/app
    environment:
      - DB_HOST=crdb-lb
      - DB_PORT=26257
      - DB_NAME=auth
      - DB_USERNAME=authUser
      - LOG_PATH=/tmp/app/logs
      - PORT=4000
    depends_on:
      - crdb-init
    restart: always
    networks:
      - backend

  server-1:
    container_name: server-1
    image: node:latest
    command: npm start
    volumes:
      - ./package.json:/usr/app/package.json
      - ./package-lock.json:/usr/app/package-lock.json
      - ./server:/usr/app/server
      - /usr/app/node_modules
      - ./volumes/server-1/logs:/tmp/app/logs
    working_dir: /usr/app
    environment:
      - DB_HOST=crdb-lb
      - DB_PORT=26257
      - DB_NAME=auth
      - DB_USERNAME=authUser
      - LOG_PATH=/tmp/app/logs
      - PORT=4000
    depends_on:
      - crdb-init
    restart: always
    networks:
      - backend

  server-2:
    container_name: server-2
    image: node:latest
    command: npm start
    volumes:
      - ./package.json:/usr/app/package.json
      - ./package-lock.json:/usr/app/package-lock.json
      - ./server:/usr/app/server
      - /usr/app/node_modules
      - ./volumes/server-2/logs:/tmp/app/logs
    working_dir: /usr/app
    environment:
      - DB_HOST=crdb-lb
      - DB_PORT=26257
      - DB_NAME=auth
      - DB_USERNAME=authUser
      - LOG_PATH=/tmp/app/logs
      - PORT=4000
    depends_on:
      - crdb-init
    restart: always
    networks:
      - backend

  server-lb:
    container_name: server-lb
    hostname: server-lb
    image: haproxy
    volumes:
      - ./server-lb.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8080:80"
      - "8081:8081"
    depends_on:
      - server-0
      - server-1
      - server-2
    restart: always
    networks:
      - backend

networks:
  db:
  backend:
