version: "3.8"

services:
  crdb-0:
    container_name: crdb-0
    hostname: crdb-0
    image: cockroachdb/cockroach:latest
    command: start-single-node --cluster-name=auth-haproxy --logtostderr=WARNING --log-file-verbosity=WARNING --insecure
    restart: always

  crdb-1:
    container_name: crdb-1
    hostname: crdb-1
    image: cockroachdb/cockroach:latest
    command: start --cluster-name=auth-haproxy --logtostderr=WARNING --log-file-verbosity=WARNING --insecure --join=crdb-0
    depends_on:
      - crdb-0
    restart: always

  crdb-2:
    container_name: crdb-2
    hostname: crdb-2
    image: cockroachdb/cockroach:latest
    command: start --cluster-name=auth-haproxy --logtostderr=WARNING --log-file-verbosity=WARNING --insecure --join=crdb-0
    depends_on:
      - crdb-0
    restart: always

  lb:
    container_name: lb
    hostname: lb
    image: timveil/dynamic-haproxy:latest
    ports:
      - "26257:26257"
      - "1080:8080"
      - "1081:8081"
    environment:
      - NODES=crdb-0 crdb-1 crdb-2
    depends_on:
      - crdb-0
      - crdb-1
      - crdb-2
    restart: always

  crdb-init:
    container_name: crdb-init
    hostname: crdb-init
    image: timveil/cockroachdb-remote-client:latest
    environment:
      - COCKROACH_HOST=crdb-0:26257
      - COCKROACH_INSECURE=true
      - DATABASE_NAME=auth
      - DATABASE_USER=authUser
    depends_on:
      - lb
    restart: always
